version: '3'
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    env_file: .env
    depends_on:
     - postgres
    command: /usr/src/app/start-app.sh

  postgres:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      TZ: "Australia/Melbourne"
      #  these are our database credentials.
      #  for the purposes of this workshop, this is not relevant and shouldn't be changed.
      #  it is just here as we are staging the database via docker.
      #  in a prod environment this would be done differently (or not in Docker at all).
      #  ðŸŒŒ these aren't the droids you are looking for ðŸŒŒ
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
