# This is a basic workflow to help you get started with Actions

name: Lint and Test

# Controls when the action will run. Triggers the workflow on push or pull request on any branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  lint_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Python dependencies
      run: |
        # Ubuntu requires a lot of hand holding to get Python 3 installed. :(
        sudo apt-get update
        sudo apt-get install gcc libpq-dev -y
        sudo apt-get install python-dev  python-pip -y
        sudo apt-get install python3-dev python3-pip python3-venv python3-wheel python3-setuptools -y
        pip3 install wheel
        pip3 install --upgrade pip
        pip3 install -r web/requirements.txt
        pip3 install flake8 pytest
        # This tells GitHub Actions to add the PATH entry for pip binaries
        echo "::add-path::${HOME}/.local/bin"
    - name: Lint with Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistic
